MVC_EF_Ex/Project.UI/Models/ControllerModels.cs
using Project.Business.Concrete;
using Project.Entites.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.UI.Models
{
    public class ControllerModels
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int CategoryId { get; set; }
        public int IsDeleted { get; set; }
        public string Description { get; set; }


    }
}

MVC_EF_Ex/Project.UI/Controllers/CategoryController.cs
using FluentValidation.Results;
using Project.Business.Concrete;
using Project.Business.Validation;
using Project.Entites.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.UI.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager();
        ProductManager pm = new ProductManager();
        public ActionResult Index()
        {
            var categories = cm.GetAllByfilter(x => x.IsDeleted == 0);
            return View(categories);
        }
        public ActionResult AddCategory() 
        {
            List<SelectListItem> value = (from x in cm.GetAll()
                                          select new SelectListItem
                                          {
                                              Value = x.Id.ToString(),
                                              Text = x.Name
                                          }).ToList();
            ViewBag.a = value;
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidation validation = new CategoryValidation();
            ValidationResult sonuc = validation.Validate(category);
            if (sonuc.IsValid)
            {
                cm.Insert(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in sonuc.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }
        [HttpPost]
        public ActionResult Delete(int categoryId)
        {
            Category category = cm.Get(x => x.Id == categoryId && x.IsDeleted == 0);
            //List<Product> list = pm.GetAllByfilter(x => x.CategoryId == categoryId);
            
            category.IsDeleted = 1;
            cm.Update(category);
            return Redirect("Index");
        }
        public ActionResult UpdateCategory(int id)
        {
            var category = cm.Get(x => x.Id == id);

            return View(category);
        }

        [HttpPost]
        public ActionResult Update(Category category)
        {
            CategoryValidation validations = new CategoryValidation();
            ValidationResult result = validations.Validate(category);
            if (result.IsValid)
            {
                cm.Update(category);
                return Redirect("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }
    }
}

MVC_EF_Ex/Project.UI/Controllers/CustomerController.cs
using Project.Business.Concrete;
using Project.Entites.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.UI.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        CustomerManager cm = new CustomerManager();
        public ActionResult Index()
        {
            List<Customer> customers = cm.GetAll();
            return View(customers);
        }
    }
}

MVC_EF_Ex/Project.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.UI.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC_EF_Ex/Project.UI/Controllers/ProductController.cs
using Project.Business.Concrete;
using Project.Entites.Concrete;
using Project.UI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Project.UI.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager();
        //ProductManager pm = new ProductManager(new EFProductDal());
        CategoryManager cm = new CategoryManager();
        [HttpGet]
        public ActionResult Index()
        {
            List<Product> products = pm.GetAll();
            List<Category> categories = cm.GetAll();
            List<ControllerModels> lists = (from c in categories
                                            join p in products on c.Id equals p.CategoryId
                                            where c.IsDeleted == 0
                                            select new ControllerModels
                                            {
                                                Id = p.Id,
                                                Price = p.Price,
                                                ProductName = p.Name,
                                                CategoryName = c.Name,
                                                Quantity = p.Quantity,
                                                IsDeleted = p.IsDeleted
                                            }).ToList();
            var result = lists.Where(x => x.IsDeleted == 0);
            return View(result.ToList());
        }
        public ActionResult AddProduct()
        {
            //List<SelectListItem> value = (from x in cm.GetAll()
            //                              select new SelectListItem
            //                              {
            //                                  Value = x.Id.ToString(),
            //                                  Text = x.Name
            //                              }).ToList();
            //ViewBag.a = value;

            var result = cm.GetAll();
            result.Where(x => x.IsDeleted == 0);
            return View(result);
        }
        [HttpPost]
        public ActionResult Add(string name, int categoryId, decimal price, int quantity)
        {
            Product product = new Product
            {
                Name = name,
                CategoryId = categoryId,
                Price = price,
                Quantity = quantity
            };
            pm.Insert(product);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Delete(int productId)
        {
            var result = pm.Get(x => x.Id == productId && x.IsDeleted == 0);
            result.IsDeleted = 1;
            pm.Update(result);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Update(int productId, string productName, decimal price, int quantity, int categoryId)
        {
            Product product = pm.Get(x => x.Id == productId && x.IsDeleted == 0);
            product.Name = productName;
            product.Price = price;
            product.Quantity = quantity;

            pm.Update(product);
            return Redirect("Index");
        }
    }
}

MVC_EF_Ex/Project.UI/Views/Category/AddCategory.cshtml
@using Project.Entites.Concrete
@model Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddCategory</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        @using (Html.BeginForm("AddCategory", "Category", FormMethod.Post, new { @class = "form-group" }))
        {
            <div class="col-md-12">
                @Html.Label("Name")
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name)
            </div>
            <div class="col-md-12">
                @Html.Label("Description")
                @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Description,"",new {@style="color:red;"})
            </div>
            @*@Html.Label("Kategori")
                @Html.DropDownListFor(x => x.Id, (List<SelectListItem>)ViewBag.a,new {@class= "form-control"}) burası product eklemek için  *@
            <button type="submit">Ekle</button>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Category/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model List<Project.Entites.Concrete.Category>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <h1 class="h1 text-left">Kategoriler</h1>
        <table class="table table-bordered">
            <tr>
                <th>Id</th>
                <th>Kategori</th>
                <th>Açıklama</th>
                <th>Güncelle</th>
                <th>SİL</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        <a href="/Category/UpdateCategory/@item.Id" class="btn-success"> Güncelle
                        </a>
                    </td>
                    <td>
                        <form method="post">
                            <input id="categoryId" name="categoryId" hidden="true" value="@item.Id" />
                            <button type="submit" formaction="/Category/Delete" class="btn-danger">SİL</button>
                        </form>
                    </td>
                </tr>
            }
        </table>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Category/UpdateCategory.cshtml
@using Project.Entites.Concrete
@model Category
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateCategory</title>
</head>
<body>
    <div class="col-md-12">
        <div class="form-group-lg">
            @using (Html.BeginForm("Update", "Category", FormMethod.Post))
            {
                @Html.TextBoxFor(x => x.Id, new { @hidden = "true" })
                @Html.Label("Adı")
                @Html.TextAreaFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name)
                @Html.Label("Açıklaması")
                @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Description)
                <button type="submit" class="btn-success">Güncelle</button>
            }
        </div>
    </div>
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Customer/Index.cshtml
@using Project.Entites.Concrete
@model List<Customer>
@{
    Layout = "~/Views/Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <h1></h1>
        @foreach (var item in Model)
        {
            <table class="table table-striped">
                <tr class="row">
                    <th>Id</th>
                    <th>İsim</th>
                    <th>Şifre</th>
                </tr>
                <tr class="row">
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Password</td>
                </tr>
            </table>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_EF_Ex/Project.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_EF_Ex/Project.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h2 class="text-left h2">Ürün</h2>
        <p><a class="btn btn-default" href="/Product/Index">Ürünler</a></p>
    </div>
    <div class="col-md-4">
        <h2 class="text-left h2">Ürünleri Ekle ve Çıkar</h2>
        <p><a class="btn btn-default" href="/Product/AddProduct">Ürün Ekle &raquo;</a></p>
    </div>
</div>

MVC_EF_Ex/Project.UI/Views/Product/AddProduct.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model List<Project.Entites.Concrete.Category>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ürün Ekle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <form class="form-group">
            <label for="name" class="label-primary">Ürün Adı</label>
            <input type="text" class="form-control text-left" id="name" name="name" placeholder="Ürün Adı" />
            <label for="category" class="label-default">Kategori</label>
            <select  class="form-control" id="categoryId" name="categoryId">
                @foreach (var item in Model)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <label for="price" class="label-default">Fiyat</label>
            <input type="number" class="form-control text-left" id="price" name="price" placeholder="Fiyat" />
            <label for="quantity" class="label-default">Adet</label>
            <input type="number" class="form-control text-left" id="quantity" name="quantity" placeholder="Adet" />
            <button id="btnSend" onclick="btnclick()" name="btnSend">Ekle</button>
        </form>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript">
        var name = $("#name");
        var price = $("#price");
        var quantity = $("#quantity");
        var btn = document.getElementById("btnSend");
        function btnclick() {
            var name = $("#name").val();
            var price = $("#price").val();
            var quantity = $("#quantity").val();

            if (name && price && quantity) {
                $("form").attr("action", "/Product/Add");
                $("form").attr("method", "post");
                $("form").submit();
            } else {
                alert("Boş olamaz!");
                window.location.reload();
            }
        }
    </script>
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Product/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model List<Project.UI.Models.ControllerModels>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ürünler</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <h2 class="modal-header text-center">Ürünler</h2>
        <table class="table table-responsive table-bordered">
            <tr class="row">
                <th>Id</th>
                <th>Adı</th>
                <th>Kategorisi</th>
                <th>Fiyatı</th>
                <th>Miktarı</th>
                <th>Güncelle</th>
                <th>Sil</th>
            </tr>
            @foreach (var item in Model)
            {
                @*@Html.DropDownListFor(@item.CategoryId,(List<SelectListItem>)ViewBag.a, new { @class = "dropdown" }) burası productda selectlistitemın kullanılması içindir *@
                <tr class="row">
                    <td>@item.Id</td>
                    <td>@item.ProductName</td>
                    <td>@item.CategoryName</td>
                    <td>@item.Price</td>
                    <td>@item.Quantity</td>
                    <td><a class="btn-success" href="/Product/Update">Güncelle</a></td>
                    <td>
                        <form method="post">
                            <input id="productId" name="productId" hidden="true" value="@item.Id" />
                            <button type="submit" id="btnSend" name="btnSend" class="btn-danger" formaction="/Product/Delete">
                                SİL
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </table>
        <form method="post">
            <table class="table table-responsive table-bordered">

                <tr>
                    <td><input type="number" id="productId" name="productId" placeholder="Id" /></td>
                    <td><input type="text" id="productName" name="productName" placeholder="Ürün Adı" /></td>
                    <td><input type="number" id="price" name="price" placeholder="Fiyat" /></td>
                    <td><input type="number" id="quantity" name="quantity" placeholder="Adet" /></td>
                    <td>
                        <select id="categoryId" name="categoryId">
                            @foreach (var item in Model)
                            {
                                <option value="@item.CategoryId">@item.CategoryName</option>
                            }
                        </select>
                    </td>
                    <td>
                        <button type="submit" id="btnUpdate" name="btnUpdate" class="btn-success" formaction="/Product/Update">
                            Güncelle
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Product/Update.cshtml
@{
    Layout = "~/Views/Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MVC_EF_Ex/Project.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ürün", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Ekle", "AddProduct", "Product")</li>
                    <li>@Html.ActionLink("Ürünler", "Index", "Product")</li>
                    <li>@Html.ActionLink("Kategori", "Index", "Category")</li>
                    <li>@Html.ActionLink("Kategori Ekle", "AddCategory", "Category")</li>
                    <li>@Html.ActionLink("Müşteriler", "Index", "Customer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Deneme</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>